apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: backend
  name: backend
spec:
  ports:
    - name: devops-tools
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
