name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: make configure-ci
      
    - name: Run fmt
      run: make fmt

    - name: Run vet
      run: make vet

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      
    - name: Run test_resources
      run: make test
